### ISSUE TITLE
замечания по паттерну strategy

### ISSUE THREAD

**Issue by alexey-malov** [ivan-uskov/ood-labs#1]
В функциональной реализации тайпдефы DanceBehavior и FlyBehavior лучше разместить в файле duck.h

**Comment by alexey-malov** [comment]
в функциональной версии quack behavior также следует сделать функциями

**Comment by alexey-malov** [comment]
Dance() следует сделать невиртуальным в функциональной версии

**Comment by alexey-malov** [comment]
на будущее лучше промежуточные вресии сохранять

**Comment by ivan-uskov** [comment]
Промежуточные версии хранит git, замечания поправил

**Comment by alexey-malov** [comment]
принято
